language: generic
sudo: required
services:
        - docker
before_install:
        - docker build -t hnaji/react-test -f ./client/Dockerfile.dev ./client
script:
        - docker run -e CI=true hnaji/react-test npm test
after_success:
        - docker build -t hnaji/multi-client ./client
        - docker build -t hnaji/multi-worker ./worker
        - docker build -t hnaji/multi-nginx ./nginx
        - docker build -t hnaji/multi-server ./server
# Login in to the Docker CLI
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin
# Take thos images and push them to the Docker hub
        - docker push hnaji/multi-client
        - docker push hnaji/multi-nginx
        - docker push hnaji/multi-server
        - docker push hnaji/multi-worker

